### ISSUE TITLE
还是不可以。。。。

### ISSUE THREAD

**Issue by WhiteSnowGirl** [gmars/yii2-aliyunmns#2]
返回false。

**Comment by gmars** [comment]
你的阿里云有没有余额看看。我这边调试通过了的。不行你就用阿里云的appkey和secretkey试试 别用子账户。endpoint要在控制台中去查询。





At 2017-04-08 15:09:57, "jsonK" <notifications@github.com> wrote:


返回false。

**Comment by gmars** [comment]
你再update一下，是有一个bug我刚修复了下。 @WhiteSnowGirl

**Comment by WhiteSnowGirl** [comment]
`$mnsObj = new AliyunMessageService(User::appkey,User::secretkey,"https://xxxxxxxxxxx.mns.cn-hangzhou.aliyuncs.com/");

        $randStr = str_shuffle('1234567890');//短信验证码由数字组成
        $code = substr($randStr,0,6);

        $rest = $mnsObj->sendSmsMessage('海星卫浴专业优选','SMS_59960606','18876412894', [ 'code' => '55', 'time' => '9' ]);

        if ($rest === false) { 
            var_dump($mnsObj->errors); 
        }else{
            echo 1;
        }
        
        var_dump($rest);exit();`
上面是我注册的代码，然后他返回
`string 'XMLReader::read(): file:///D:/wamp/www/haixing/web/:1: parser error : Document is empty' (length=87)`
`boolean false`

**Comment by WhiteSnowGirl** [comment]
我update了。

**Comment by WhiteSnowGirl** [comment]
![image](https://cloud.githubusercontent.com/assets/12612585/24827078/b1cfb584-1c76-11e7-85fd-7a661b4da713.png)

**Comment by WhiteSnowGirl** [comment]
余额5块。

**Comment by WhiteSnowGirl** [comment]
sendSmsMessage()這个方法里面的，直接在这边返回false了。不知到为什么，是我aliyun控制台没设置啥吗？
`if ($this->createTopic() == false) {
            return false;
        }`

**Comment by gmars** [comment]
调用你实例化的AliyunMessageService对象的errors看看错误详情
 var_dump($mnsObj->errors);
我刚刚试了试我这边确实可以发送短信

**Comment by WhiteSnowGirl** [comment]
我使用的是主题账号的ak ，var_dump($mnsObj->errors);  是
`string 'XMLReader::read(): file:///D:/wamp/www/haixing/web/:1: parser error : Document is empty' (length=87)`

**Comment by WhiteSnowGirl** [comment]
![image](https://cloud.githubusercontent.com/assets/12612585/24827334/e7f934b6-1c79-11e7-82c8-d968594a0cb8.png)

**Comment by WhiteSnowGirl** [comment]
上面的那个错误是在实例化AliyunMessageService对象的时候就有errors了
`XMLReader::read(): file:///D:/wamp/www/haixing/web/:1: parser error : Document is empty`

**Comment by WhiteSnowGirl** [comment]
大兄弟，那个错误详情，我看不懂是啥原因？

**Comment by gmars** [comment]
我刚刚在Windows中测试了，这个错误是由于你的php没有xmlreader扩展造成的。我在Linux系统下使用了--with-xmlreader来编译的所以有xmlreader扩展。但是在Windows系统下需要引入xmlreader扩展。你可以先在网上查看下php中安装xmlreader扩展的方法。

**Comment by WhiteSnowGirl** [comment]
我刚刚看了下php -m看了下有xmlreader，本地也看了下php -m看了下，也有，
`xml
xmlreader
xmlrpc
xmlwriter`
但是我没有找到xmlreader.dll的文件，

**Comment by WhiteSnowGirl** [comment]
我还没弄到线上。

**Comment by WhiteSnowGirl** [comment]
我 刚刚用脚本测试了一下。
`$reader = new XMLReader();   
var_dump($reader);`
他返回xmlreader对象。

**Comment by WhiteSnowGirl** [comment]
我本地看了下 php -m 发现有xmlreader，然后也用脚本实力化了xmlreader返回了一个对象，说明我本地是有xml的。

**Comment by WhiteSnowGirl** [comment]
@gmars  还是不行

**Comment by WhiteSnowGirl** [comment]
xmlreader哪里安装。百度了好久。

**Comment by WhiteSnowGirl** [comment]
我有xml但是我调用$xmlRead->Read()方法的时候会有错误。

**Comment by WhiteSnowGirl** [comment]
我大概知道了，xmlreader->reader()這个方法不能用在阿里云的sdk里面，但很奇怪，我的php版本5.5.12，php -m 也有libxml 和xmlreader這两个扩展，官网说這两个扩展不用弄在php.ini。直接就开启了默认安装，我本地也是集成化wamp安装。但是 没有结局办法。

**Comment by WhiteSnowGirl** [comment]
把https 改成http，就可以了，但是我短信没有发送成功。

**Comment by zerozh** [comment]
我在本地调试的时候遇到了相似的问题，

最后一条错误信息是 `MnsException: XMLReader::read() ... parser error : Document is empty`

查看完整调用发现根源在于 `cURL error 28: Resolving timed out after 3000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)` 

也就是http请求没完成，所以返回了空的xml，自然xml解析失败了。

阿里云配置和账户余额都没有问题，endpoint无论是https还是http都试了。

最后的解决办法是：一模一样的代码和配置在阿里云的机器上测试，跑通了。

**Comment by WhiteSnowGirl** [comment]
可以的，www.alidayu.com 你要用這个。才可以。
